#!/usr/bin/env python
"""Batch generate missing wordbooks 48-51, 54, 56-61 for IELTS vocab meme system"""

import json
import os

BASE_DIR = r"E:\certify\src\ielts\vocab-meme\wordbook"

# Load missing words list
with open(os.path.join(BASE_DIR, "missing_words.txt"), encoding="utf-8") as f:
    all_missing = [line.strip() for line in f if line.strip()]

# Load word meanings for reference
with open(os.path.join(BASE_DIR, "word_meanings.json"), encoding="utf-8") as f:
    word_meanings = json.load(f)

# Word data: (phonetic, chinese_meaning, meme, example) for each word in all_missing
# This is the complete dataset covering words 1-1464

WORD_DATA = {
    # ===== WORDBOOK 48 (1-100, #4701-#4800): humid -> inverse =====
    "humid": ("/ˈhjuːmɪd/", "adj. 潮湿的/湿润的", "「休美的」—— 休息的地方美但很潮湿 💧", "The <b>humid</b> climate made it difficult to sleep without air conditioning."),
    "hurdle": ("/hɜːdl/", "n. 障碍/栏架 v. 跨越障碍", "「喝抖」—— 喝了酒发抖，跨不过障碍 🚧", "The final <b>hurdle</b> before getting the job was a tough interview."),
    "husband": ("/ˈhʌzbənd/", "n. 丈夫", "「哈笨」—— 哈哈，笨蛋丈夫 👨", "Her <b>husband</b> surprised her with flowers on their anniversary."),
    "hush": ("/hʌʃ/", "v./n. 安静/肃静/嘘", "「哈事」—— 哈？什么事？嘘 🤫", "The teacher said '<b>hush</b>' to quiet the noisy classroom."),
    "hustle": ("/ˈhʌsl/", "v. 忙碌/催促 n. 忙乱/推搡", "「哈搜」—— 哈哈哈搜索，忙忙碌碌 🏃", "She had to <b>hustle</b> to catch the last bus home."),
    "hymn": ("/hɪm/", "n. 赞美诗/圣歌", "「黑幕」—— 黑幕里唱赞美诗 ⛪", "The choir sang a beautiful <b>hymn</b> at the wedding."),
    "hypocrisy": ("/hɪˈpɒkrəsi/", "n. 伪善/虚伪", "「嗨泼可瑞斯」—— 嗨泼可瑞斯的虚伪 😶", "His criticism of corruption was seen as pure <b>hypocrisy</b>."),
    "hysteria": ("/hɪˈstɪəriə/", "n. 歇斯底里/过度兴奋", "「黑死提瑞儿」—— 黑死提瑞儿歇斯底里 😱", "The announcement caused mass <b>hysteria</b> among fans."),
    "idiomatic": ("/ˌɪdiəˈmætɪk/", "adj. 符合语言习惯的/地道的/惯用的", "「一弟欧麦题可」—— 一弟欧麦题可的地道表达 ✍️", "'Break a leg' is an <b>idiomatic</b> expression meaning good luck."),
    "idol": ("/ˈaɪdl/", "n. 偶像/神像/崇拜对象", "「爱斗」—— 爱斗的人是偶像 ⭐", "The pop star became an <b>idol</b> for millions of teenagers."),
    "ignite": ("/ɪɡˈnaɪt/", "v. 点燃/引发/激动", "「一哥奈特」—— 一哥奈特点燃了激情 🔥", "The speech <b>ignited</b> a wave of protests across the country."),
    "illegible": ("/ɪˈledʒəbl/", "adj. 字迹难辨认的/难以阅读的", "「一来只伯」—— 一来只伯伯的字迹难辨认 📝", "His handwriting was so <b>illegible</b> that I couldn't read the note."),
    "illusive": ("/ɪˈluːsɪv/", "adj. 造成幻觉的/虚幻的/迷惑人的", "「一路死无」—— 一路上死了无数，虚幻的梦 💭", "The mirage was an <b>illusive</b> image of water in the desert."),
    "immediately": ("/ɪˈmiːdiətli/", "adv. 立即/马上/直接地", "「一米迪特里」—— 一米距离特立即到 🏃", "Please call me <b>immediately</b> if there's any problem."),
    "immoral": ("/ɪˈmɒrəl/", "adj. 不道德的/邪恶的", "「一磨肉」—— 一磨肉是不道德的行为 😈", "Stealing from the poor is deeply <b>immoral</b>."),
    "immortal": ("/ɪˈmɔːtl/", "adj. 不朽的/永生的 n. 不朽的人物", "「一摩投」—— 一摩投不朽的作品 📖", "Shakespeare's works are virtually <b>immortal</b>."),
    "impede": ("/ɪmˈpiːd/", "v. 阻碍/妨碍/阻止", "「一批地的」—— 一批地的东西阻碍了道路 🚧", "Bad weather could <b>impede</b> the rescue operation."),
    "imperative": ("/ɪmˈperətɪv/", "adj. 极重要的/紧急的 n. 祈使语气/必要的事", "「一摸怕若踢五」—— 一摸怕若踢五是紧急的 🚨", "It is <b>imperative</b> that we act now before it's too late."),
    "imperial": ("/ɪmˈpɪəriəl/", "adj. 帝国的/皇家的/宏伟的", "「一摸皮俄瑞」—— 一摸皮俄瑞帝国的 🏰", "The museum houses a magnificent <b>imperial</b> collection of artifacts."),
    "implore": ("/ɪmˈplɔː/", "v. 恳求/哀求/乞求", "「一摸破」—— 一摸破了恳求帮忙 🙏", "She <b>implored</b> him not to leave her alone."),
    "impractical": ("/ɪmˈpræktɪkl/", "adj. 不切实际的/不实用的", "「一摸怕可题扣」—— 一摸怕可题扣不实际 💡", "Your plan sounds nice but is completely <b>impractical</b>."),
    "imprisonment": ("/ɪmˈprɪznmənt/", "n. 监禁/关押/徒刑", "「一摸普瑞森门特」—— 一摸普瑞森门特被监禁 🔒", "He was sentenced to ten years' <b>imprisonment</b> for his crimes."),
    "improvise": ("/ˈɪmprəvaɪz/", "v. 即兴创作/临时凑合/即席发言", "「一摸普若外兹」—— 一摸普若外兹即兴演奏 🎵", "The actor forgot his lines and had to <b>improvise</b>."),
    "inadvertent": ("/ˌɪnədˈvɜːtənt/", "adj. 无意的/疏忽的/不经意的", "「因爱的我腾特」—— 因爱我腾特无意做了 😅", "An <b>inadvertent</b> error caused the system to crash."),
    "inaugurate": ("/ɪˈnɔːɡjʊreɪt/", "v. 为...举行就职典礼/开创/启动", "「因诺格觉锐特」—— 因诺格觉锐特就任总统 🎩", "The new president will be <b>inaugurated</b> next month."),
    "incense": ("/ˈɪnsens/", "n. 香 v. 激怒", "「因森斯」—— 因森林烧香 🕯️", "The monk lit some <b>incense</b> during meditation."),
    "incessant": ("/ɪnˈsesnt/", "adj. 不断的/连续不停的", "「因塞森特」—— 因塞森特不断来 🔄", "The <b>incessant</b> noise from construction kept us awake all night."),
    "incidentally": ("/ˌɪnsɪˈdentli/", "adv. 偶然地/顺便说一句", "「因森丹特里」—— 因森丹特里偶然遇到 👋", "<b>Incidentally</b>, have you heard the latest news?"),
    "inclination": ("/ˌɪnkliˈneɪʃn/", "n. 倾向/爱好/斜坡", "「因可内内神」—— 因可内内神的倾向 ❤️", "She has a strong <b>inclination</b> toward art and music."),
    "inclined": ("/ɪnˈklaɪnd/", "adj. 倾向于...的/有...意向的", "「因克兰得」—— 因克兰得倾向于同意 👍", "I'm <b>inclined</b> to believe her story."),
    "incompatible": ("/ˌɪnkəmˈpætəbl/", "adj. 不相容的/不协调的/矛盾的", "「因肯摸拍特伯」—— 因肯摸拍特伯不相容 ⚡", "The two software versions are completely <b>incompatible</b>."),
    "inconsistency": ("/ˌɪnkənˈsɪstənsi/", "n. 不一致/前后矛盾/反复无常", "「因肯森斯特恩斯」—— 因肯森斯特恩斯不一致 🔄", "There are several <b>inconsistencies</b> in your statement."),
    "inconvenient": ("/ˌɪnkənˈviːniənt/", "adj. 不方便的/打扰的", "「因肯维尼恩特」—— 因肯维恩特不方便 😣", "Would tomorrow at three o'clock be <b>inconvenient</b> for you?"),
    "incredulous": ("/ɪnˈkredjʊləs/", "adj. 不轻信的/表示怀疑的", "「因可瑞丢勒斯」—— 因可丢勒斯表示怀疑 🤨", "She gave me an <b>incredulous</b> look when I told her the news."),
    "increment": ("/ˈɪŋkrɪmənt/", "n. 增量/增加/加薪", "「因克热门特」—— 因克热门特增量 📈", "Each <b>increment</b> in salary is based on performance."),
    "incur": ("/ɪnˈkɜː/", "v. 招致/遭受/引起", "「因壳」—— 因外壳招致损坏 💸", "The company may <b>incur</b> significant losses this quarter."),
    "indebted": ("/ɪnˈdetɪd/", "adj. 感激的/负债的", "「因戴提得」—— 因戴提得欠债感激 🙏", "I am deeply <b>indebted</b> to my mentor for her guidance."),
    "indefinitely": ("/ɪnˈdefɪnətli/", "adv. 无限期地/不确定地", "「因代费你特里」—— 因代费你特里无限期 ⏳", "The meeting has been postponed <b>indefinitely</b>."),
    "indent": ("/ɪnˈdent/", "v. 缩进 n. 订单/契约/凹痕", "「因登特」—— 因登特缩进排版 📄", "Remember to <b>indent</b> the first line of each paragraph."),
    "indicative": ("/ɪnˈdɪkətɪv/", "adj. 指示的/表明的/ indicative", "「因地可踢五」—— 因地可踢五是表明的 📊", "These results are <b>indicative</b> of a larger trend."),
    "indictment": ("/ɪnˈdaɪtmənt/", "n. 起诉/控告/起诉书", "「因地特门特」—— 因地特门特被起诉 ⚖️", "The grand jury returned an <b>indictment</b> against the CEO."),
    "indifference": ("/ɪnˈdɪfrəns/", "n. 冷漠/漠不关心/无关紧要", "「因地佛润斯」—— 因地佛润斯冷漠 😐", "His <b>indifference</b> to the problem frustrated everyone."),
    "indigestion": ("/ˌɪndɪˈdʒestʃən/", "n. 消化不良/无法理解", "「因地接斯神」—— 因地接斯神消化不良 🤢", "Eating too quickly often causes <b>indigestion</b>."),
    "indignant": ("/ɪnˈdɪɡnənt/", "adj. 愤慨的/义愤填膺的", "「因地嗯特」—— 因地嗯特愤慨 😠", "She was <b>indignant</b> at the accusation of lying."),
    "indignation": ("/ˌɪndɪɡˈneɪʃn/", "n. 愤慨/义愤", "「因地内神】—— 因地内神义愤 😡", "The unfair decision aroused public <b>indignation</b>."),
    "inducement": ("/ɪnˈdjuːsmənt/", "n. 引诱/诱因/激励", "「因丢斯门特」—— 因丢斯门特的诱惑 🎁", "Financial <b>inducement</b> was offered to attract investors."),
    "indulge": ("/ɪnˈdʌldʒ/", "v. 放纵/沉溺于/满足欲望", "「因大智」—— 因大智者放纵自己 🍰", "On weekends I like to <b>indulge</b> in my favorite desserts."),
    "industrialization": ("/ɪnˌdʌstriəlaɪˈzeɪʃn/", "n. 工业化", "「因达斯特瑞来神」—— 因达斯特瑞来神工业化 🏭", "Rapid <b>industrialization</b> transformed the country's economy."),
    "industrialized": ("/ɪnˈdʌstriəlaɪzd/", "adj. 工业化的", "「因达斯特来兹」—— 因达斯特来兹工业化国家 🏭", "Most <b>industrialized</b> nations face aging population problems."),
    "industrious": ("/ɪnˈdʌstriəs/", "adj. 勤奋的/勤劳的/努力的", "「因达斯特瑞斯」—— 因达斯特瑞斯勤劳工作 🐝", "The <b>industrious</b> bee collects nectar all day long."),
    "inertia": ("/ɪnɜːʃə/", "n. 惯性/惰性/迟钝", "「呢射」—— 呢射出惯性 ⚽", "<b>Inertia</b> keeps the planet moving around the sun."),
    "infantry": ("/ˈɪnfəntri/", "n. 步兵/步兵团", "「因凡吹」—— 因凡吹是步兵 🪖", "The <b>infantry</b> advanced cautiously through the forest."),
    "infection": ("/ɪnˈfekʃn/", "n. 感染/传染病/影响", "「因飞可神」—— 因飞可神感染病毒 🦠", "Wash your hands to prevent the spread of <b>infection</b>."),
    "inference": ("ˈɪnfərəns/", "n. 推断/推理/结论", "「因佛润斯」—— 因佛润斯推断结果 🔍", "What <b>inference</b> can you draw from these facts?"),
    "inferiority": ("/ˌɪnfɪəriˈɒrəti/", "n. 低劣/自卑/次等", "「因非俄瑞提」—— 因非俄瑞提自卑感 😔", "Feelings of <b>inferiority</b> can hold people back from success."),
    "infinity": ("/ɪnˈfɪnəti/", "n. 无穷/无限大量", "「因非你提」—— 因非你提无限 ♾️", "The universe seems to stretch into <b>infinity</b>."),
    "inflict": ("/ɪnˈflɪkt/", "v. 使遭受/造成/施加", "「因夫利可特」—— 因夫利可特造成伤害 💥", "The hurricane <b>inflicted</b> severe damage on coastal areas."),
    "influential": ("/ˌɪnfluˈenʃl/", "adj. 有影响力的/有权势的", "「因夫伦收」—— 因夫伦收有影响力的 👑", "She is one of the most <b>influential</b> writers of our time."),
    "influenza": ("/ˌɪnfluˈenzə/", "n. 流行性感冒", "「因夫伦则」—— 因夫伦则是流感 🤧", "She caught a bad case of <b>influenza</b> during winter."),
    "influx": ("/ˈɪnflʌks/", "n. 涌入/汇集/流入", "「因夫拉克斯」—— 因夫拉克斯涌入人群 👥", "There has been a huge <b>influx</b> of tourists this summer."),
    "informative": ("/ɪnˈfɔːmətɪv/", "adj. 提供信息的/增长知识的", "「因佛迈提五」—— 因佛迈提五提供信息 📚", "The lecture was very <b>informative</b> about space exploration."),
    "infringe": ("/ɪnˈfrɪndʒ/", "v. 侵犯/违反/ infringement", "「因夫润之」—— 因夫润之侵犯了版权 ⚖️", "Don't <b>infringe</b> on other people's privacy."),
    "ingenious": ("/ɪnˈdʒiːniəs/", "adj. 巧妙的/独创的/心灵手巧的", "「因真牛斯」—— 因真牛斯太巧妙的 🧠", "She came up with an <b>ingenious</b> solution to the problem."),
    "ingenuity": ("/ˌɪndʒəˈnjuːəti/", "n. 独创性/心灵手巧/精巧", "「因真牛爱提」—— 因真牛爱提有独创力 💡", "The engineer showed great <b>ingenuity</b> in designing the bridge."),
    "initially": ("/ɪˈnɪʃəli/", "adv. 最初/开始时/首先", "「一尼收里」—— 一尼收里最初的想法 💭", "<b>Initially</b>, we thought the project would take only two weeks."),
    "initiate": ("/ɪˈnɪʃieɪt/", "v. 开始/发起/接纳 n. 新加入者", "「一尼收诶特」—— 一尼收诶特开始行动 🚀", "The government plans to <b>initiate</b> a new education program."),
    "injustice": ("/ɪnˈdʒʌstɪs/", "n. 不公正/不公平/非正义", "「因扎死替斯」—— 因扎死替斯不公平 ⚖️", "Protesters gathered against social <b>injustice</b>."),
    "innocuous": ("/ɪˈnɒkjuəs/", "adj. 无害的/无害处的/无伤大雅的", "「闹可饿斯」—— 闹可饿斯是无害的小白兔 🐇", "It seemed like an <b>innocuous</b> comment but caused offense."),
    "innovative": ("/ˈɪnəveɪtɪv/", "adj. 创新的/革新的", "「爱诺喂提五」—— 爱诺喂提五创新的 💡", "This company is known for its <b>innovative</b> products."),
    "innumerable": ("/ɪˈnjuːmrəbl/", "adj.无数的/数不清的", "「因纽莫若伯」—— 因纽莫若伯数不清的星星 ⭐", "There are <b>innumerable</b> stars visible on a clear night."),
    "insane": ("/ɪnˈseɪn/", "adj. 疯狂的/荒唐的/精神病的", "「因森」—— 因森林里疯狂的 😵", "The prices in that city are absolutely <b>insane</b>."),
    "insider": ("/ɪnˈsaɪdə/", "n. 内部人士/知情人", "「因赛德」—— 因赛德内部人员 👤", "An <b>insider</b> revealed details of the merger deal."),
    "insignificant": ("/ˌɪnsɪɡˈnɪfɪkənt/", "adj. 不重要的/微不足道的/无意义的", "「因森哥尼非肯特」—— 因森哥尼非肯特不重要 🤏", "The cost was <b>insignificant</b> compared to the benefits."),
    "insolvent": ("/ɪnˈsɒlvənt/", "adj. 无力偿付的/破产的", "「因索文特」—— 因索文特破产了 💸", "The company went <b>insolvent</b> after years of losses."),
    "inspection": ("/ɪnˈspekʃn/", "n. 检查/视察/检验", "「因斯拜可神」—— 因斯拜可神检查 🔍", "All factories must pass regular safety <b>inspections</b>."),
    "inspector": ("/ɪnˈspektə/", "n. 检查员/巡视员/督察", "「因斯拜可特」—— 因斯拜可特检查员 👮", "The health <b>inspector</b> found several violations."),
    "installation": ("/ˌɪnstəˈleɪʃn/", "n. 安装/装置/就职", "「因斯托雷神」—— 因斯托雷神安装设备 🔧", "The <b>installation</b> of the new system took three days."),
    "installment": ("/ɪnˈstɔːlmənt/", "n. 分期付款/分期连载/安装", "「因斯托门特」—— 因斯托门特分期付款 💳", "You can pay for the car in monthly <b>installments</b>."),
    "instigate": ("/ˈɪnstɪɡeɪt/", "v. 教唆/煽动/发起", "「因斯提给特」—— 因斯提给特煽动暴乱 🔥", "He was accused of <b>instigating</b> the riot."),
    "instinctive": ("/ɪnˈstɪŋktɪv/", "adj. 本能的/天性的/直觉的", "「因斯廷可提五」—— 因斯汀可提五本能反应 🦁", "It was an <b>instinctive</b> reaction to jump back from the edge."),
    "instructive": ("/ɪnˈstrʌktɪv/", "adj. 有教育意义的/有益的", "「因斯抓可提五」—— 因斯抓可提五有教育的 📖", "The documentary was very <b>instructive</b> about wildlife."),
    "instrumental": ("/ˌɪnstruˈmentl/", "adj. 起重要作用的/用乐器演奏的", "「因斯楚门投」—— 因斯楚门投起重要作用 🎼", "He was <b>instrumental</b> in negotiating the peace treaty."),
    "insufficient": ("/ˌɪnsəˈfɪʃnt/", "adj. 不足的/不够的/无能的", "「因瑟非神特」—— 因瑟非神特资金不足 💸", "We have <b>insufficient</b> data to draw any conclusions."),
    "insulate": ("/ɪnsjuleɪt/", "v. 隔离/绝缘/使隔离", "「因修累特」—— 因修累特隔离起来 🧱", "Wear gloves to <b>insulate</b> your hands from the cold."),
    "insulation": ("/ˌɪnsjuˈleɪʃn/", "n. 绝缘/隔热/隔离", "「因修累神」—— 因修累神隔热材料 🏠", "Good roof <b>insulation</b> can reduce heating costs."),
    "intellect": ("/ˈɪntəlekt/", "n. 智力/才智/知识分子", "「因泰莱可特」—— 因泰莱可特智力超群 🧠", "She is respected for her sharp <b>intellect</b>."),
    "intensive": ("/ɪnˈtensɪv/", "adj. 密集的/加强的/彻底的", "「因ten死五」—— 因ten死五密集训练 🏋️", "The patient underwent <b>intensive</b> care after surgery."),
    "intent": ("/ɪnˈtent/", "n. 意图/目的 adj. 专注的/决心的", "「因ten特」—— 因ten特有意图的 🎯", "His <b>intent</b> was clear: he wanted to help."),
    "interference": ("/ˌɪntəˈfɪərəns/", "n. 干扰/干涉/妨碍", "「因泰非润斯」—— 因泰菲润斯干扰信号 📻", "Thank you for your help, but please stop <b>interfering</b>."),
    "interim": ("/ˈɪntərɪm/", "adj. 暂时的/过渡的 n. 过渡期间", "「因泰瑞姆」—— 因泰瑞姆过渡期 ⏰", "An <b>interim</b> government was appointed before elections."),
    "interpretation": ("/ɪnˌtɜːprɪˈteɪʃn/", "n. 解释/理解/演绎", "「因特普瑞teishen」—— 因特普瑞teishen解释 📖", "There are different <b>interpretations</b> of this poem."),
    "intrude": ("/ɪnˈtruːd/", "v. 闯入/侵入/把...强加于", "「因出入的」—— 因出入的不该闯入 🚫", "Sorry to <b>intrude</b>, but I need to ask you something."),
    "inundate": ("/ˈɪnʌndeɪt/", "v. 淹没/泛滥/使应接不暇", "「因昂deit」—— 因昂deit淹没城市 🌊", "The office was <b>inundated</b> with complaints after the announcement."),
    "invader": ("/ɪnˈveɪdə/", "n. 入侵者/侵略者/侵入物", "「因威德」—— 因威德入侵者 ⚔️", "The castle was built to defend against foreign <b>invaders</b>."),
    "invalid": ("/ɪnˈvælɪd/", "adj. 无效的/作废的 n. 病弱者", "「因外里的」—— 因外里的无效 🚫", "This ticket is <b>invalid</b>; it expired yesterday."),
    "invalidate": ("/ɪnˈvælideɪt/", "v. 使无效/使作废/推翻", "「因外里deit」—— 因外里deit使无效 ❌", "New evidence may <b>invalidate</b> the previous verdict."),
    "invaluable": ("/ɪnˈvæljuəbl/", "adj. 无价的/极宝贵的", "「因外流伯」—— 因外流伯是无价之宝 💎", "Her advice proved <b>invaluable</b> during the crisis."),
    "invariably": ("/ɪnˈveəriəbli/", "adv. 总是/不变地/一贯地", "「因外俄里伯里」—— 因外俄里伯里总是这样 😐", "He is <b>invariably</b> late for every meeting."),
    "inventory": ("/ˈɪnvəntəri/", "n. 存货清单/库存/详细目录", "「因ven推瑞」—— 因ven推瑞库存清单 📦", "We need to do a full <b>inventory</b> of warehouse stock."),
    "inverse": ("/ˈɪnvɜːs/", "adj. 相反的/颠倒的 n. 反面/相反的事物", "「因沃斯」—— 因沃斯是相反的 ↔️", "There is an <b>inverse</b> relationship between price and demand."),

    # ===== WORDBOOK 49 (101-200, #4801-#4900): investigation -> majority =====
    "investigation": ("/ɪnˌvestɪˈɡeɪʃn/", "n. 调查/研究/审查", "「因ves提gation」—— 因ves提gation调查 🔍", "Police launched a full <b>investigation</b> into the theft."),
    "invoice": ("/ˈɪnvɔɪs/", "n. 发票/账单 v. 开发票", "「因vois」—— 因vois开发票 🧾", "Please send the <b>invoice</b> to our accounts department."),
    "irregular": ("/ɪˈreɡjələ/", "adj. 不规则的/无规律的", "「一瑞格友乐」—— 一瑞格友乐不规则的 🔺", "His heartbeat became <b>irregular</b> after running."),
    "irresistible": ("/ˌɪrɪˈzɪstəbl/", "adj. 无法抗拒的/令人着迷的", "「一瑞zi斯特伯」—— 一瑞zi斯特伯无法抗拒 😍", "The chocolate cake looked simply <b>irresistible</b>."),
    "irrespective": ("/ˌɪrɪˈspektɪv/", "adj./prep. 不管的/不顾的", "「一瑞spec提五」—— 一瑞spec提五不管 🚫", "Everyone is welcome, <b>irrespective</b> of age or background."),
    "irrevocable": ("/ɪˈrevəkəbl/", "adj. 不可撤销的/不可改变的", "「一瑞vo可伯」—— 一瑞vo伯不可撤销 🔒", "Signing this contract is an <b>irrevocable</b> commitment."),
    "irrigate": ("/ˈɪrɪɡeɪt/", "v. 灌溉/冲洗", "「一瑞给特」—— 一瑞给特灌溉农田 💧", "Farmers use canals to <b>irrigate</b> their fields."),
    "irritate": ("/ˈɪrɪteɪt/", "v. 激怒/刺激/使发痒", "「一瑞teit」—— 一瑞teit让人烦躁 😤", "Loud music really <b>irritates</b> me when I'm studying."),
    "isolation": ("/ˌaɪsəˈleɪʃn/", "n. 隔离/孤立/隔绝", "「爱so雷神」—— 爱so雷神的孤立 🏝️", "The village's <b>isolation</b> preserved its unique culture."),
    "ivory": ("/ˈaɪvəri/", "n. 象牙/乳白色 adj. 乳白色的", "「爱我瑞」—— 爱我的象牙白 🦣", "The piano keys were once made of real <b>ivory</b>."),
    "jealousy": ("/ˈdʒeləsi/", "n. 嫉妒/猜忌/小心守护", "「宅乐西」—— 宅乐西嫉妒别人 💚", "His <b>jealousy</b> damaged their friendship."),
    "jelly": ("/ˈdʒeli/", "n. 果冻/果酱/ jelly", "「宅里」—— 宅里有果冻 🍮", "She spread strawberry <b>jelly</b> on her toast."),
    "jerk": ("/dʒɜːk/", "v. 猛拉/急扯 n. 怪人/突然动作", "「哲可」—— 哲可猛地一拽 🎯", "The bus gave a sudden <b>jerk</b> and everyone fell forward."),
    "jettison": ("/ˈdʒetɪsn/", "v. 抛弃/丢弃/ jettison", "「杰提森」—— 杰提森抛弃货物 📦", "The airline decided to <b>jettison</b> some routes."),
    "jewelry": ("/ˈdʒuːəlri/", "n. 珠宝首饰/珠宝业", "「住瑞」—— 住瑞家有很多珠宝 💎", "She inherited a beautiful collection of <b>jewelry</b> from her grandmother."),
    "juicy": ("/ˈdʒuːsi/", "adj. 多汁的/有趣的/生动的", "「住西」—— 住西边吃多汁的水果 🍊", "The steak was tender and <b>juicy</b>."),
    "jumble": ("/ˈdʒʌmbl/", "v. 混杂/混淆 n. 混乱一堆", "「榨伯」—— 榨伯混杂在一起 🔀", "The papers were all <b>jumbled</b> up on the desk."),
    "junction": ("/ˈdʒʌŋkʃn/", "n. 连接点/交叉口/枢纽站", "「咱可神」—— 咱可神在交叉路口 🚦", "Meet me at the <b>junction</b> of Main Street and Oak Avenue."),
    "justifiable": ("/ˈdʒʌstɪfaɪəbl/", "adj. 可证明为正当的/有理由的", "「扎死提fiab」—— 扎死提fiab正当的 ⚖️", "In times of war, extreme measures may be <b>justifiable</b>."),
    "justification": ("/ˌdʒʌstɪfɪˈkeɪʃn/", "n. 正当理由/辩解/辩护", "「扎死提keishen」—— 扎死提keishen的理由 📝", "What is your <b>justification</b> for being so late?"),
    "kangaroo": ("/ˌkæŋɡəˈruː/", "n. 袋鼠", "「看哥入」—— 看哥入袋鼠袋 🦘", "The <b>kangaroo</b> hopped across the Australian outback."),
    "kernel": ("/kɜːnl/", "n. 核心/果核/ kernel", "«可哦» —— 可哦是核心 🌰", "The <b>kernel</b> of the argument is quite simple."),
    "kerosene": ("/ˈkerəsiːn/", "n. 煤油/ kerosene", "「可热seen」—— 可热seen煤油灯 🪔", "The lamp used <b>kerosene</b> as fuel."),
    "kidnap": ("/ˈkɪdnæp/", "v. 绑架/拐骗", "「kid拿扑」—— kid拿扑去绑架 🆘", "The wealthy businessman was <b>kidnapped</b> for ransom."),
    "kidney": ("/ˈkɪdni/", "n. 肾脏/腰子", "「kid你」—— kid你的肾脏 🫘", "Drinking plenty of water helps keep your <b>kidneys</b> healthy."),
    "knack": ("/næk/", "n. 技能/窍门/习惯", "「耐可」—— 耐可有窍门 🔧", "She has a <b>knack</b> for fixing broken things."),
    "knob": ("/nɒb/", "n. 把手/旋钮/球形突出物", "「诺伯」—— 诺伯转旋钮 🎛️", "Turn the <b>knob</b> clockwise to increase the volume."),
    "laborer": ("/ˈleɪbərə/", "n. 劳动者/劳工/工人", "「雷博热」—— 雷博热的劳动者 👷", "The <b>laborer</b> worked twelve hours in the hot sun."),
    "lace": ("/leɪs/", "n. 鞋带/蕾丝 v. 系带", "「雷斯」—— 雷斯系鞋带 👟", "Can you help me tie my shoe <b>lace</b>?"),
    "lag": ("/læɡ/", "v. 落后/滞后 n. 时间差/延迟", "「赖格」—— 赖格落后了 🐢", "Internet speeds tend to <b>lag</b> during peak hours."),
    "lame": ("/leɪm/", "adj. 跛的/瘸的/差劲的", "「雷木」—— 雷木跛脚走 🦽", "He felt <b>lame</b> after making such an obvious excuse."),
    "landing": ("/ˈlændɪŋ/", "n. 登陆/着陆/降落平台", "「蓝定」—— 蓝定的降落 ✈️", "The pilot made a smooth <b>landing</b> despite strong winds."),
    "landmark": ("/ˈlɑːnmɑːk/", "n. 地标/里程碑/标志性建筑", "「兰mark」—— 兰mark地标 🗼", "The Eiffel Tower is a famous Paris <b>landmark</b>."),
    "lapse": ("/læps/", "n./v. 失误/流逝/失效", "「赖普斯」—— 赖普斯失误了 😅", "A brief <b>lapse</b> in concentration caused the accident."),
    "lark": ("/lɑːk/", "n. 云雀/百灵鸟/欢乐时光", "「拉克」—— 拉克像云雀一样快乐 🐦", "They got up at <b>lark</b> to watch the sunrise."),
    "lasting": ("/ˈlɑːstɪŋ/", "adj. 持久的/永久的", "「拉斯听」—— 拉斯听的持久影响 🕐", "Their friendship left a <b>lasting</b> impression on both of them."),
    "lateral": ("/ˈlætərəl/", "adj. 侧面的/横向的 n. 侧部", "「lat若」—— lat若侧面看 👁️", "The building features a <b>lateral</b>> extension on each floor."),
    "lavish": ("/ˈlævɪʃ/", "adj. 奢华的/慷慨的 v. 挥霍/大方给予", "「拉vi失」—— 拉vi失奢华生活 💎", "They threw a <b>lavish</b> party for their anniversary."),
    "leaflet": ("/ˈliːflət/", "n. 传单/小册子", "「里夫lit」—— 里夫lit发传单 📄", "Volunteers distributed <b>leaflets</b> door to door."),
    "leap": ("/liːp/", "v. 跳跃/剧增 n. 跳跃/飞跃", "「里普」—— 里普跳跃 🐆", "The cat made a graceful <b>leap</b> onto the windowsill."),
    "legacy": ("/ˈleɡəsi/", "n. 遗产/遗留/ legacy", "「来格si」—— 来格si留下遗产 🏛️", "The author left behind a rich literary <b>legacy</b>."),
    "legendary": ("/ˈledʒəndəri/", "adj. 传说中的/传奇的", "「来zen得瑞」—— 来zen得瑞传说中 🐉", "The musician achieved almost <b>legendary</b> status in jazz history."),
    "lengthen": ("/ˈleŋθn/", "v. 加长/延长", "「冷森」—— 冷森延长冬天 ❄️", "We need to <b>lengthen</b>> the deadline by another week."),
    "leopard": ("/ˈlepəd/", "n. 豹/豹纹", "「来婆的」—— 来婆的是豹子 🐆", "The <b>leopard</b> moved silently through the tall grass."),
    "lever": ("/ˈliːvə/", "n. 杠杆/手段/工具 v. 用杠杆撬动", "「里沃」—— 里沃用杠杆 🏗️", "Use this <b>lever</b> to lift the heavy rock."),
    "liability": ("/ˌlaɪəˈbɪləti/", "n. 责任/债务/不利条件", "「来a博里提」—— 来a博里提责任 ⚖️", "The company faces significant legal <b>liabilities</b>."),
    "liable": ("/ˈlaɪəbl/", "adj. 有责任的/可能的/易...的", "「来a伯」—— 来a伯有责任的 👮", "Drivers are <b>liable</b> for any damage they cause."),
    "liberate": ("/ˈlɪbəreɪt/", "v. 解放/释放/使自由", "「里ber瑞特」—— 里ber瑞特解放了 🔓", "The army managed to <b>liberate</b> the occupied city."),
    "lick": ("/lɪk/", "v. 舔/舔舐/轻松战胜", "「里克」—— 里克舔冰淇淋 🍦", "The dog started to <b>lick</b> my hand happily."),
    "lift": ("/lɪft/", "v. 举起/抬起/电梯 n. 电梯/搭便车", "「里福特」—— 里福特举起 🏋️", "Can you give me a <b>lift</b> to the station?"),
    "light": ("/laɪt/", "adj. 轻的/浅色的 n. 光/灯光 v. 点燃", "「莱特」—— 莱特兄弟让飞机变轻 ✈️", "The suitcase is surprisingly <b>light</b>."),
    "likelihood": ("/ˈlaɪklihʊd/", "n. 可能性/可能", "「来可lihood」—— 来可lihood可能性高 🎲", "There is a strong <b>likelihood</b> of rain tonight."),
    "limestone": ("/ˈlaɪmstəʊn/", "n. 石灰岩", "「莱母斯顿」—— 莱母斯顿石灰岩 🪨", "The cliffs are made of white <b>limestone</b>."),
    "limousine": ("/ˈlɪməziːn/", "n. 豪华轿车/ limousine", "「里慕森」—— 里慕森豪华车 🚗", "They arrived at the prom in a stretch <b>limousine</b>."),
    "limp": ("/lɪmp/", "v. 跛行/ adj. 软弱的/无力的", "「林普」—— 林普跛行 🚶", "The injured player continued to <b>limp</b> off the field."),
    "line": ("/laɪn/", "n. 线/路线/行业 v. 排队/画线", "「莱恩」—— 莱恩画线 ✏️", "Draw a straight <b>line</b> across the page."),
    "linear": ("/ˈlɪniə/", "adj. 线性的/直线的/长度的", "「里尼额」—— 里尼额线性关系 📈", "The story has a simple <b>linear</b> structure."),
    "linen": ("/ˈlɪnɪn/", "n. 亚麻布/床单 adj. 亚麻的", "「林恩」—— 林恩的亚麻布床单 🛏️", "The table was covered with fresh white <b>linen</b>."),
    "liner": ("/ˈlaɪnə/", "n. 班轮/衬垫/ liner", "「莱纳」—— 莱纳班轮 🚢", "The luxury <b>liner</b> sailed across the Atlantic."),
    "linger": ("/ˈlɪŋɡə/", "v. 逗留/徘徊/消逝", "「零哥」—— 零哥徘徊不走 🚶", "Visitors <b>lingered</b> in the garden, enjoying the sunset."),
    "linguistics": ("/lɪŋˈɡwɪstɪks/", "n. 语言学", "「零guiss提克斯」—— 零guiss提克斯语言学 🗣️", "She is studying <b>linguistics</b> at university."),
    "liquid": ("/ˈlɪkwɪd/", "n. 液体 adj. 液体的/流动的", "「likwid」—— likwid液体 💧", "Water is the most essential <b>liquid</b> for life."),
    "liquor": ("/ˈlɪkə/", "n. 烈酒/酒类/液汁", "「likor」—— likor烈酒 🍸", "The bar offers a wide selection of imported <b>liquors</b>."),
    "list": ("/lɪst/", "n. 列表/清单 v. 列出/列举", "「里斯特」—— 里斯特列出清单 📋", "Please make a <b>list</b> of everything you need."),
    "literally": ("/ˈlɪtərəli/", "adv. 逐字地/确实/简直", "「里特若里」—— 里特若里确实如此 📖", "There were <b>literally</b> thousands of people at the concert."),
    "literate": ("/ˈlɪtərət/", "adj. 识字的/有文化的 n. 识字的人", "「里特瑞特」—— 里特瑞特识字 📚", "Every citizen should be <b>literate</b> in the digital age."),
    "literature": ("/ˈlɪtrətʃə/", "n. 文学/文献/著作", "「里trecher」—— 里trecher文学作品 📚", "Shakespeare is a giant of English <b>literature</b>."),
    "livelihood": ("/ˈlaɪvlihʊd/", "n. 生计/生活方式/谋生之道", "「来活lihood」—— 来活lihood就是生计 💰", "Fishing is the main source of <b>livelihood</b> for coastal villagers."),
    "lively": ("/ˈlaɪvli/", "adj. 充满活力的/生动的/热闹的", "「来福利」—— 来福利充满活力 🎉", "The discussion was <b>lively</b> and engaging."),
    "liver": ("/ˈlɪvə/", "n. 肝脏/肝", "「里沃」—— 里沃的肝脏 🫁", "Too much alcohol can damage your <b>liver</b>."),
    "livestock": ("/ˈlaɪvstɒk/", "n. 家畜/牲畜", "「来夫sto克」—— 来夫sto克家畜 🐄", "The farm raises various types of <b>livestock</b>."),
    "load": ("/ləʊd/", "n. 负担/装载量 v. 装载/加载", "「楼的」—— 楼的重载很重 📦", "The truck was fully <b>loaded</b> with supplies."),
    "loaf": ("/ləʊf/", "n. 一条面包 v. 游荡/虚度光阴", "「楼夫」—— 楼夫烤面包 🍞", "She bought a fresh <b>loaf</b> of bread at the bakery."),
    "lobster": ("/ˈlɒbstə/", "n. 龙虾/龙虾肉", "「劳bs特」—— 劳bs特龙虾 🦞", "We ordered grilled <b>lobster</b> for dinner."),
    "locality": ("/ləʊˈkæləti/", "n. 地区/地点/位置", "「楼卡里提」—— 楼卡里提地区 📍", "The whole <b>locality</b> was affected by the flood."),
    "location": ("/ləʊˈkeɪʃn/", "n. 位置/地点/选址", "「楼kei神」—— 楼kei神的位置 📍", "The hotel is in a convenient <b>location</b> near the station."),
    "lock": ("/lɒk/", "n. 锁 v. 锁上/固定", "「劳克」—— 劳克锁门 🔒", "Don't forget to <b>lock</b> the door when you leave."),
    "locomotive": ("/ˌləʊkəˈməʊtɪv/", "n. 火车头/机车 adj. 运动的", "「楼口mo提五」—— 楼口mo提五火车头 🚂", "Steam <b>locomotives</b> were replaced by electric ones."),
    "locust": ("/ˈləʊkəst/", "n. 蝗虫/蚱蜢", "「楼卡斯特」—— 楼卡斯特蝗虫群 🦗", "A swarm of <b>locusts</b> destroyed the crops."),
    "lodge": ("/lɒdʒ/", "v. 住宿/存放/正式提出 n. 小屋/门房", "「劳治」—— 劳治住在小屋 🏠", "They decided to <b>lodge</b> a formal complaint with the police."),
    "lodging": ("/ˈlɒdʒɪŋ/", "n. 住宿/寄宿处", "「劳jing」—— 劳jing住宿 🛏️", "Budget <b>lodgings</b>> are available for travelers."),
    "lofty": ("/ˈlɒfti/", "adj. 高耸的/崇高的/傲慢的", "「劳夫提」—— 劳夫提崇高理想 🏔️", "She set herself <b>lofty</b> goals for the future."),
    "log": ("/lɒɡ/", "n. 日志/原木 v. 记录/伐木", "「劳格」—— 劳格记录日志 📝", "Please <b>log</b> all maintenance activities in the notebook."),
    "longevity": ("/lɒnˈdʒevəti/", "n. 长寿/持久/寿命", "「龙杰vi提」—— 龙杰vi提长寿 🎂", "Good nutrition contributes to <b>longevity</b>."),
    "loop": ("/luːp/", "n. 环/循环 v. 成环/绕圈", "「路普」—— 路普循环一圈 🔄", "The roller coaster goes through three complete <b>loops</b>."),
    "loosen": ("/ˈluːsn/", "v. 放松/松开/放宽", "「鲁森」—— 鲁森放松一下 😌", "Please <b>loosen</b> your tie; it looks too tight."),
    "lose": ("/luːz/", "v. 失去/输掉/迷失", "「路斯」—— 路斯输了比赛 😢", "Don't <b>lose</b> hope; things will get better."),
    "low": ("/ləʊ/", "adj. 低的/矮的 adv. 低声地 n. 低点", "「楼」—— 楼很低 🏢", "Prices reached an all-time <b>low</b> last month."),
    "loyal": ("/ˈlɔɪəl/", "adj. 忠诚的/忠实的", "「罗哟」—— 罗哟很忠诚 🐕", "Dogs are known for being <b>loyal</b> companions."),
    "lubricate": ("/ˈluːbrɪkeɪt/", "v. 润滑/使顺畅/涂抹润滑剂", "「路布瑞keit」—— 路布瑞keit润滑 🔧", "Regularly <b>lubricate</b> the chain to prevent rust."),
    "lumber": ("/ˈlʌmbə/", "n. 木材/ lumber v. 笨重移动/伐木", "「朗伯」—— 朗伯木材 🪵", "The house was built using local <b>lumber</b>."),
    "luminous": ("/ˈluːmɪnəs/", "adj. 发光的/明亮的/夜光的", "「路敏斯」—— 路敏斯发光的 ✨", "The moon cast a <b>luminous</b> glow over the ocean."),
    "lunar": ("/ˈluːnə/", "adj. 月亮的/阴历的/月球上的", "「路纳」—— 路纳月亮 🌙", "The Chinese calendar follows a <b>lunar</b> cycle."),
    "luxurious": ("/lʌɡˈʒʊəriəs/", "adj. 奢侈的/豪华的/舒适的", "「拉格日瑞斯」—— 拉格日瑞斯奢华 💎", "The hotel room was <b>luxurious</b> with marble floors."),
    "mackintosh": ("/ˈmækɪntɒʃ/", "n. 防水胶布外套/雨衣", "「马金托什」—— 马金托什雨衣 🧥", "Don't forget your <b>mackintosh</b>; it looks like rain."),
    "magic": ("/ˈmædʒɪk/", "n. 魔法/魔术 adj. 有魔力的", "「买ji可」—— 买ji可有魔法 ✨", "The show combined music and <b>magic</b> beautifully."),
    "magician": ("/məˈdʒɪʃn/", "n. 魔术师/巫师", "「ma ji神」—— ma ji神魔术师 🎩", "The <b>magician</b> amazed the audience with his tricks."),
    "magistrate": ("/ˈmædʒɪstreɪt/", "n. 地方法官/治安法官", "「ma ji strait」—— ma ji strait法官 ⚖️", "The case will be heard by a local <b>magistrate</b>."),
    "magnetism": ("/ˈmæɡnɪtɪzəm/", "n. 磁性/磁力/吸引力", "「ma格内提zm」—— ma格内提zm磁性 🧲", "The <b>magnetism</b> of his personality drew people to him."),
    "magnify": ("/ˈmæɡnɪfaɪ/", "v. 放大/夸大/加强", "「ma格内fi」—— ma格内fi放大 🔍", "The microscope can <b>magnify</b> objects up to a thousand times."),
    "maize": ("/meɪz/", "n. 玉米/玉米色/黄色", "「mei滋」—— mei滋玉米甜 🌽", "<b>Maize</b> is a staple crop in many countries."),
    "majesty": ("/ˈmædʒəsti/", "n. 威严/ Majesty(陛下)", "「ma jes提」—— ma jes提陛下 👑", "Your <b>Majesty</b>, the people await your command."),
    "majority": ("/məˈdʒɒrəti/", "n. 大多数/多数/成年", "「ma jor瑞提」—— ma jor瑞提大多数 🗳️", "The vast <b>majority</b> voted in favor of the proposal."),

    # ===== WORDBOOK 50 (201-300, #4901-#5000): malaise -> motto =====
    "malaise": ("/mæˈleɪz/", "n. 不适/不安/莫名的不舒服", "「ma leiz」—— ma leiz身体不适 🤒", "A sense of economic <b>malaise</b> spread across the nation."),
    "malice": ("/ˈmælɪs/", "n. 恶意/怨恨/ premeditation", "「ma利斯」—— ma利斯有恶意 😈", "She bore no <b>malice</b> toward her former colleague."),
    "manifestation": ("/ˌmænɪfeˈsteɪʃn/", "n. 表现/显示/ manifest", "「mani费steishen」—— mani费steishen表现 🎭", "The disease's first <b>manifestation</b> is usually a fever."),
    "manifesto": ("/ˌmænɪˈfestəʊ/", "n. 宣言/声明/告示", "「mani费斯托」—— mani费斯托宣言 📜", "The party published its election <b>manifesto</b> last week."),
    "mansion": ("/ˈmænʃn/", "n. 大厦/豪宅/官邸", "「曼森」—— 曼森豪宅 🏰", "They bought a beautiful Victorian <b>mansion</b> in the countryside."),
    "map": ("/mæp/", "n. 地图 v. 绘制地图/映射", "「map」—— map就是地图 🗺️", "Let's check the <b>map</b> to find the fastest route."),
    "maple": ("/ˈmeɪpl/", "n. 枫树/枫木/淡棕色", "「mei普」—— mei普枫叶 🍁", "Canada is famous for its <b>maple</b> syrup."),
    "marble": ("/ˈmɑːbl/", "n. 大理石/弹珠", "「马伯」—— 马伯大理石雕塑 🗿", "The floor was polished <b>marble</b>."),
    "march": ("/mɑːtʃ/", "v. 行军/前进 n. 三月/进行曲", "「马驰」—— 马驰行军 🪖", "The soldiers began to <b>march</b> at dawn."),
    "mariner": ("/ˈmærɪnə/", "n. 水手/海员", "「马瑞na」—— 鏃瑞na水手 ⚓", "The old <b>mariner</b> told tales of sea monsters."),
    "maritime": ("/ˈmærɪtaɪm/", "adj. 海事的/航海的/沿海的", "「ma瑞tim」—— ma瑞tim海事 ⚓", "<b>Maritime</b> trade is vital for the island's economy."),
    "marked": ("/mɑːkt/", "adj. 显著的/有记号的 v. 标记/做记号", "「马克的」—— 马克的显著标记 ✓", "There has been a <b>marked</b> improvement in his grades."),
    "marsh": "/mɑːʃ/", "n. 沼泽/湿地", "「马氏」—— 马氏沼泽 🌿", "The bird hides in the thick <b>marsh</b> grass."),
    "marshal": ("/mɑːʃl/", "n. 元帅/执行官 v. 整理/排列", "「马绍」—— 马绍元帅 🎖️", "The general served as field <b>marshal</b> during the war."),
    "martyr": ("/mɑːtə/", "n. 殉道者/烈士 v. 以殉道精神忍受", "「马特」—— 马特烈士 ⚱️", "He died a <b>martyr</b> for his beliefs."),
    "marvel": ("/mɑːvl/", "v. 惊叹 n. 奇迹/令人惊奇的事物", "「马沃」—— 马沃惊叹奇迹 😮", "We <b>marveled</b> at the beauty of the Grand Canyon."),
    "masculine": ("/ˈmæskjʊlɪn/", "adj. 男性的/阳刚的/男子气概的", "「ma skyou lin」—— ma skyou lin男性 💪", "He has deep voice and strongly <b>masculine</b> features."),
    "mask": ("/mɑːsk/", "n. 口罩/面具/伪装 v. 掩饰/遮盖", "「mask」—— mask口罩 😷", "Everyone wore a face <b>mask</b> to prevent infection."),
    "massacre": ("/ˈmæsəkə/", "n. 大屠杀/惨败 v. 屠杀/彻底击败", "「ma sa可」—— ma sa可大屠杀 💀", "The battle ended in a terrible <b>massacre</b>."),
    "mast": ("/mɑːst/", "n. 桅杆/ mast", "「mast」—— mast桅杆 ⛵", "The sailor climbed the <b>mast</b> to fix the sail."),
    "match": ("/mætʃ/", "n. 比赛/火柴/匹配 v. 匹配/比得上", "「ma chi」—— ma chi比赛 🏆", "The football <b>match</b> drew a crowd of fifty thousand."),
    "material": ("/məˈtɪəriəl/", "n. 材料/原料/素材 adj. 物质的/重要的", "「ma ti瑞尔」—— ma ti瑞尔材料 🧱", "We need more <b>materials</b> to finish the project."),
    "materialism": ("/məˈtɪəriəlɪzəm/", "n. 唯物主义/物质主义/实利主义", "「ma ti瑞ali zm」—— ma ti瑞ali zm物质至上 💰", "Critics argue that <b>materialism</b> corrupts society's values."),
    "mathematics": ("/ˌmæθəˈmætɪks/", "n. 数学/数学运算", "「ma si ma tiks」—— ma si ma tics数学 ➕", "She excelled in <b>mathematics</b> throughout school."),
    "mattress": ("/ˈmætrɪs/", "n. 床垫/褥子/空气垫", "「ma tris」—— ma tris床垫 🛏️", "A good <b>mattress</b> is essential for quality sleep."),
    "maturity": ("/məˈtʃʊərəti/", "n. 成熟/完备/到期", "「ma chu瑞提」—— ma chu瑞提成熟 🧠", "His handling of the crisis showed remarkable <b>maturity</b>."),
    "meadow": ("/ˈmedəʊ/", "n. 草地/牧场/草地", "「me do」—— me do草地 🌿", "Cows grazed peacefully in the green <b>meadow</b>."),
    "measure": ("/ˈmeʒə/", "n. 测量/措施/程度 v. 测量/衡量", "「me折」—— me折测量 📏", "Can you <b>measure</b> the length of this table?"),
    "mechanical": ("/məˈkænɪkl/", "adj. 机械的/机械般的/体力的", "「me kan ni ko」—— me kan ni ko机械的 ⚙️", "The factory uses automated <b>mechanical</b> arms for assembly."),
    "mechanics": ("/məˈkænɪks/", "n. 力学/机械学/技术细节", "「me kan ni克斯」—— me kan ni克斯力学 🔧", "Understanding basic <b>mechanics</b> helps with car maintenance."),
    "medal": ("/ˈmedl/", "n. 奖章/勋章/纪念章", "「me dou」—— me dou奖牌 🏅", "She won a gold <b>medal</b> in the Olympics."),
    "medieval": ("/ˌmediˈiːvl/", "adj. 中世纪的/古老的/过时的", "「me di i vo」—— me di i vo中世纪 🏰", "The castle dates back to the <b>medieval</b> period."),
    "meditate": ("/ˈmedɪteɪt/", "v. 冥想/沉思/谋划", "「me di teit」—— me di teit冥想 🧘", "He likes to <b>meditate</b> for twenty minutes every morning."),
    "meditation": ("/ˌmedɪˈteɪʃn/", "n. 冥想/沉思/冥想曲", "「me di teishen」—— me di teishen沉思 🧘", "Daily <b>meditation</b> helps reduce stress levels."),
    "meek": ("/miːk/", "adj. 温顺的/谦和的/柔和的", "「密可」—— 密可温顺的 🐑", "Despite his fierce appearance, he was surprisingly <b>meek</b>."),
    "melancholy": ("/ˈmelənkɒli/", "n. 忧郁/悲哀 adj. 忧郁的", "「me lang可里」—— me lang可里忧郁 😢", "A feeling of <b>melancholy</b> settled over the group."),
    "melody": ("/ˈmelədi/", "n. 旋律/歌曲/美妙的音乐", "「me low di」—— me low di旋律 🎵", "The <b>melody</b> of this song is unforgettable."),
    "melon": ("/ˈmelən/", "n. 瓜/甜瓜/ melon", "「me lon」—— me lon瓜 🍈", "She sliced a fresh honeydew <b>melon</b> for dessert."),
    "melt": ("/melt/", "v. 融化/溶解/消失", "「me 特」—— me特融化冰雪 🧊", "The snow began to <b>melt</b> in the spring sunshine."),
    "memo": ("/ˈmeməʊ/", "n. 备忘录/内部通告", "「me mo」—— me mo备忘录 📝", "Send a <b>memo</b> to all staff about the new policy."),
    "memorize": ("/ˈmeməraɪz/", "v. 记忆/背诵/记住", "「me魔瑞兹」—— me魔瑞兹记忆 🧠", "Students must <b>memorize</b> all the vocabulary words."),
    "memory": ("/ˈmeməri/", "n. 记忆/存储器/回忆", "「me mori」—— me mori记忆 💭", "She has an excellent <b>memory</b> for faces."),
    "mend": ("/mend/", "v. 修理/修补/改善", "「meng 的」—— meng的修补 🔧", "Can you <b>mend</b> this torn shirt for me?"),
    "mentality": ("/menˈtæləti/", "n. 心态/思想方法/心理状态", "「men ta li提」—— men ta li提心态 🧠", "You need to change your negative <b>mentality</b> to succeed."),
    "mention": ("/ˈmenʃn/", "v./n. 提及/说起/提到", "「men神」—— men神提及 🗣️", "Did she <b>mention</b> when she would arrive?"),
    "menu": ("/ˈmenjuː/", "n. 菜单/选单", "「men you」—— men you菜单 🍽️", "Let's look at the <b>menu</b> before ordering."),
    "mercantile": ("/mɜːkəntaɪl/", "adj. 商业的/贸易的/重利的", "「mer肯tail」—— mer肯tail商业的 💼", "The city grew rich through <b>mercantile</b> trade."),
    "merchandise": ("/mɜːtʃəndaɪs/", "n. 商品/货物 v. 推销/买卖", "「mer chen daiz」—— mer chen daiz商品 🛍️", "The store displays a wide variety of <b>merchandise</b>."),
    "mermaid": ("/mɜːmeɪd/", "n. 美人鱼/女游泳健将", "「mer meid」—— mer meid美人鱼 🧜‍♀️", "Children love stories about <b>mermaids</b> living under the sea."),
    "mesh": ("/meʃ/", "n. 网/网格 v. 啮合/ mesh", "「mesh」—— mesh网格 🕸️", "The gears don't <b>mesh</b> properly anymore."),
    "metallic": ("/məˈtælɪk/", "adj. 金属的/金属般的/金属质的", "「me塔lik」—— me塔lik金属的 ⚙️", "The <b>metallic</b> taste in the water comes from old pipes."),
    "metric": ("/ˈmetrɪk/", "adj. 公制的/度量的 n. 度量标准", "「me trik」—— me trik公制 📏", "Most countries use the <b>metric</b> system for measurements."),
    "microscope": ("/ˈmaɪkrəskəʊp/", "n. 显微镜", "「mai克罗skop」—— mai克罗skop显微镜 🔬", "Scientists used a <b>microscope</b> to examine the sample."),
    "microwave": ("/ˈmaɪkrəweɪv/", "n. 微波/微波炉 v. 微波加热", "「mai克罗wei五」—— mai克罗wei五微波炉 🍿", "Heat the leftovers in the <b>microwave</b> for two minutes."),
    "migrant": ("/ˈmaɪɡrənt/", "n. 移民/候鸟/移居者 adj. 移居的", "「mai格兰特」—— mai格兰特移民 🧳", "<b>Migrant</b> workers play a crucial role in agriculture."),
    "milestone": ("/ˈmaɪlstəʊn/", "n. 里程碑/转折点/重要事件", "「mai尔斯顿」—— mai尔斯顿里程碑 🏁", "Graduation is an important <b>milestone</b> in life."),
    "milk": ("/mɪlk/", "n. 牛奶 v. 挤奶/榨取", "「miou可」—— miou可牛奶 🥛", "The baby drinks a bottle of <b>milk</b> every night."),
    "miller": ("/ˈmɪlə/", "n. 磨坊主/铣工/ milling machine operator", "「mil er」—— miler磨坊主 🌾", "The <b>miller</b> ground wheat into flour."),
    "millionaire": ("/ˌmiljəˈneə/", "n. 百万富翁/富豪", "「mil ju ne厄」—— mil ju ne厄百万富翁 💰", "He became a self-made <b>millionaire</b> by age thirty."),
    "mince": ("/mɪns/", "v. 切碎/小步走路 n. 肉末", "「min斯」—— min斯切碎 🍖", "Finely <b>mince</b> the garlic before adding it to the pan."),
    "miniature": ("/ˈmɪnətʃə/", "n. 缩小的模型/微型画 adj. 微型的", "「mi ni ch厄」—— mi ni ch厄微型 🏰", "She collected <b>miniature</b> figurines of animals."),
    "minister": ("/ˈmɪnɪstə/", "n. 部长/大臣/牧师 v. 服侍/照顾", "「mi ni st厄」—— mi ni st厄部长 👔", "The Prime <b>Minister</b> addressed the nation on television."),
    "minus": ("/ˈmaɪnəs/", "prep. 减去/ n. 减号/负数 adj. 减去的/负的", "「mai nas」—— mai nas减法 ➖", "Ten <b>minus</b> three equals seven."),
    "minute": ("/ˈmɪnɪt/", "n. 分钟 adj. 微小的/详细的", "「mi ni 特」—— mi ni特分钟 ⏱️", "Wait just a <b>minute</b>; I'll be right there."),
    "miraculous": ("/mɪˈrækjʊləs/", "adj. 奇迹般的/非凡的", "「mi瑞可les」—— mi瑞可les奇迹般 ✨", "Her recovery was nothing short of <b>miraculous</b>."),
    "miscarriage": ("/ˌmɪsˈkærɪdʒ/", "n. 流产/失败/误判", "「mis ka瑞治」—— mis ka瑞治流产 😔", "The project ended in <b>miscarriage</b> due to poor planning."),
    "mischief": ("/ˈmɪstʃɪf/", "n. 恶作剧/损害/淘气", "「mis chif」—— mis chif恶作剧 😈", "Those kids are always up to some <b>mischief</b>."),
    "misery": ("/ˈmɪzəri/", "n. 痛苦/悲惨/不幸", "「mi ze瑞」—— mi ze瑞痛苦 😢", "The war brought untold <b>misery</b> to millions of people."),
    "misfortune": ("/ˌmɪsˈfɔːtʃuːn/", "n. 不幸/灾祸/逆境", "「mis fortchun」—— mis fortchun不幸 ☔", "She bore her <b>misfortunes</b> with remarkable courage."),
    "misgiving": ("/mɪsˈɡɪvɪŋ/", "n. 担忧/疑虑/疑惧", "「mis giwing」—— mis giwing担忧 😟", "Despite my <b>misgivings</b>, I agreed to go ahead."),
    "mishap": ("/ˈmɪshæp/", "n. 小事故/不幸/晦气", "「mis hap」—— mis hap小意外 🩹", "Apart from one minor <b>mishap</b>, the trip went smoothly."),
    "mislead": ("/ˌmisˈliːd/", "v. 误导/引入歧途", "「mis lid」—— mis lid误导 🚫", "Don't let those statistics <b>mislead</b> you."),
    "missile": ("/ˈmisaɪl/", "n. 导弹/投射物/导弹武器", "「mi sai」—— mi sai导弹 🚀", "The country tested a new ballistic <b>missile</b>."),
    "mist": ("/mɪst/", "n. 薄雾/雾气 v. 使蒙上薄雾", "「mist」—— mist薄雾 🌫️", "The morning <b>mist</b> lifted as the sun rose higher."),
    "moan": ("/məʊn/", "v. 呻吟/抱怨 n. 呻吟声/悲叹", "「moun」—— moun呻吟 😩", "The injured player let out a soft <b>moan</b> of pain."),
    "mobilize": ("/ˈməʊbɪlaɪz/", "v. 动员/调动/组织", "「mou bilai兹」—— mou bilai兹动员 📢", "The government began to <b>mobilize</b> emergency resources."),
    "mock": ("/mɒk/", "v. 嘲笑/模仿 adj. 模拟的/假的 n. 嘲弄", "「mock」—— mock嘲笑 😝", "It's easy to <b>mock</b> someone else's efforts."),
    "modification": ("/ˌmɒdɪfɪˈkeɪʃn/", "n. 修改/改变/修正", "「mo di fi keishen」—— mo di fi keishen修改 ✏️", "Some <b>modifications</b> were needed to improve the design."),
    "modulate": ("/ˈmɒdjuleɪt/", "v. 调节/调整/调制", "「mo jule it」—— mo jule it调节 🎛️", "Speakers should <b>modulate</b> their tone according to context."),
    "module": ("/ˈmɒdjuːl/", "n. 模块/组件/单元", "「mo jiu」—— mo jiu模块 📦", "Each course consists of six separate <b>modules</b>."),
    "moist": ("/mɔɪst/", "adj. 潮湿的/湿润的/多雨的", "「moi st」—— moi st潮湿的 💧", "Keep the soil <b>moist</b> but not waterlogged."),
    "moisture": ("/mɔɪstʃə/", "n. 水分/潮气/湿气", "「moi st ch厄」—— moi st ch厄水分 💧", "The desert air lacks enough <b>moisture</b> for plants."),
    "molecular": ("/məˈlekjʊlə/", "adj. 分子的/由分子组成的", "「mo lek you lar」—— mo lek you lar分子的 🔬", "<b>Molecular</b> biology is a fascinating field of study."),
    "momentary": ("/ˈməʊməntri/", "adj. 短暂的/瞬间的/片刻的", "「mo men特瑞」—— mo men特瑞短暂的 ⏱️", "There was a <b>momentary</b> pause before she answered."),
    "momentous": ("/məʊˈmentəs/", "adj. 重大的/关键的/重要的", "「mo men tes」—— mo men tes重大的 🏛️", "This is a <b>momentous</b> decision for our country's future."),
    "monastery": ("/ˈmɒnəstri/", "n. 修道院/僧院", "「mo na st瑞」—— mo na st瑞修道院 ⛪", "The ancient <b>monastery</b> sits atop a mountain."),
    "monopolize": ("/məˈnɒpəlaɪz/", "v. 垄断/独占/ monopolize", "「mo no po lai兹」—— mo no po lai兹垄断 🏢", "One company shouldn't <b>monopolize</b> the entire market."),
    "monotony": ("/məˈnɒtəni/", "n. 单调/千篇一律/乏味", "「mo no toni」—— mo no toni单调 😴", "The <b>monotony</b> of daily routine sometimes gets boring."),
    "monster": ("/ˈmɒnstə/", "n. 怪物/怪兽/恶人", "「mons特」—— mons特怪物 👹", "The child was afraid there was a <b>monster</b> under the bed."),
    "monstrous": ("/ˈmɒnstrəs/", "adj. 巨大的/可怕的/畸形的", "「mons chrus」—— mons chrus巨大的怪物 👾", "The storm caused <b>monstrous</b> waves along the coast."),
    "monumental": ("/ˌmɒnjuˈmentl/", "adj. 极大的/纪念碑式的/意义深远的", "「mo ju men tal」—— mo ju men tal极大的 🏛️", "Scientists made a <b>monumental</b> discovery in medicine."),
    "moor": ("/mʊə/", "v. 停泊/使固定 n. 荒野/沼泽", "「mu厄」—— mu厄停泊船 ⛵", "Fishermen <b>moored</b> their boats in the harbor."),
    "moratorium": ("/ˌmɒrəˈtɔːriəm/", "n. 暂停/禁止/ moratorium", "「mo若to瑞厄姆」—— mo若to瑞厄姆暂停 ⏸️", "The city declared a <b>moratorium</b> on new construction."),
    "motel": ("/məʊˈtel/", "n. 汽车旅馆", "「mo tel」—— mo tel汽车旅馆 🏨", "They stayed at a roadside <b>motel</b> during their road trip."),
    "motionless": ("/ˈməʊʃnləs/", "adj. 不动的/静止的", "「mo shen les」—— mo shen les静止不动 🧊", "The cat sat <b>motionless</b>, watching the bird."),
    "motivation": ("/ˌməʊtɪˈveɪʃn/", "n. 动机/动力/积极性", "「mo ti veishen」—— mo ti veishen动力 💪", "Lack of <b>motivation</b> is why many students drop out."),
    "motto": ("/ˈmɒtəʊ/", "n. 座右铭/格言/箴言", "「mo tou」—— mo tou座右铭 📜", "Our school's <b>motto</b> is 'Knowledge is Power'."),

    # ===== WORDBOOK 51 (301-400, #5001-#5100): mould -> optional =====
    "mould": ("/məʊld/", "n. 模具/霉菌/泥土 v. 用模子做/塑造", "「mo 得」—— mo 得模具 🏗️", "Pour the mixture into the <b>mould</b> and let it cool."),
    "mourn": ("/mɔːn/", "v. 哀悼/悲伤/忧伤", "「mo恩」—— mo恩哀悼 😢", "The nation <b>mourned</b> the loss of its beloved leader."),
    "mournful": ("/mɔːnfl/", "adj. 悲伤的/凄凉的/哀痛的", "「mo恩福」—— mo恩福悲伤 😞", "A <b>mournful</b> tune played softly in the background."),
    "mourning": ("/mɔːnɪŋ/", "n. 哀悼/服丧/悲伤", "「mo恩ing」—— mo恩ing哀悼 🕯️", "The family observed a period of <b>mourning</b> for thirty days."),
    "moustache": ("/məˈstɑːʃ/", "n. 胡子/八字胡/髭", "「ma sta师」—— ma sta师的胡子 🧔", "He grew a distinctive <b>moustache</b> during vacation."),
    "mouth": ("/maʊθ/", "n. 嘴/开口 v. 装腔作势地说", "「mouse」—— mouse嘴 👄", "She covered her <b>mouth</b> when she laughed."),
    "movement": ("/ˈmuːvmənt/", "n. 运动/活动/移动", "「mu v ment」—— mu v ment运动 🏃", "The civil rights <b>movement</b> changed American society forever."),
    "muffle": ("/ˈmʌfl/", "v. 包住/蒙住/压抑/消音", "「ma fo」—— ma fo包住声音 🔇", "She tried to <b>muffle</b> her cough during the exam."),
    "muffler": ("/ˈmʌflə/", "n. 围巾/消声器/ muffler", "「ma fo ler」—— ma fo ler围巾 🧣", "Wear a warm <b>muffler</b>; it's freezing outside."),
    "multiply": ("/ˈmʌltɪplaɪ/", "v. 乘/繁殖/成倍增加", "「ma ti plai」—— ma ti plai乘法 ➗", "If you <b>multiply</b> six by four, you get twenty-four."),
    "multitude": ("/ˈmʌltɪtjuːd/", "n. 大量/众多/群众", "「ma ti tiu 的」—— ma ti tiu的大量 👥", "A <b>multitude</b> of problems faced the new administration."),
    "murmur": ("/mɜːmə/", "v. 低语/私下抱怨 n. 低语/咕哝", "「mo mo」—— mo mo低语 🤫", "There was a <b>murmur</b> of approval from the audience."),
    "muscular": ("/ˈmʌskjələ/", "adj. 肌肉的/肌肉发达的/强有力的", "「ma s kyou lar」—— ma s kyou lar肌肉发达 💪", "Regular exercise keeps your body <b>muscular</b> and fit."),
    "muse": ("/mjuːz/", "v. 沉思/冥想 n. 缪斯女神", "「miu兹」—— miu兹沉思 💭", "She sat by the window, <b>musing</b> about her future."),
    "mushroom": ("/ˈmʃruːm/", "n. 蘑菇 v. 迅速成长", "「ma shru 木」—— ma shru木蘑菇 🍄", "Wild <b>mushrooms</b> can be poisonous if eaten."),
    "mute": ("/mjuːt/", "adj. 哑的/沉默的 v. 减弱/静音 n. 弱音器", "「miu 特」—— miu特哑的 🔇", "He remained <b>mute</b> throughout the entire meeting."),
    "mutton": ("/ˈmʌtn/", "n. 羊肉/羊肉肉", "「ma ten」—— ma ten羊肉 🍖", "The restaurant serves delicious roasted <b>mutton</b>."),
    "myriad": ("/ˈmiriəd/", "adj. 无数的/多种多样的 n. 无数", "「mi ri ad」—— mi ri ad无数颗星 ⭐", "There are a <b>myriad</b> of reasons to visit Japan."),
    "myth": ("/mɪθ/", "n. 神话/虚构的故事/误解", "「mis」—— mis神话 🐉", "The idea that carrots help you see in the dark is a <b>myth</b>."),
    "mythology": ("/mɪˈθɒlədʒi/", "n. 神话学/神话集/神话体系", "「mi tho lo ji」—— mi thi lo ji神话学 📚", "Greek <b>mythology</b> is filled with gods and heroes."),
    "naked": ("/ˈneɪkɪd/", "adj. 裸体的/赤裸的/暴露的", "「nei ked」—— nei ked裸体的 🛁", "The children ran <b>naked</b> into the sea."),
    "namely": ("/ˈneɪmli/", "adv. 即/也就是/换句话说", "「name里」—— name里就是 📝", "Two students, <b>namely</b> Tom and Jerry, passed the test."),
    "nap": ("/næp/", "n. 午睡/小睡 v. 打盹", "「nap」—— nap午睡 😴", "I always take a short <b>nap</b> after lunch."),
    "narrator": ("/nəˈreɪtə/", "n. 叙述者/讲述者/旁白员", "「na rei特」—— na rei特讲述者 📖", "The <b>narrator</b> described the scene in vivid detail."),
    "native": ("/ˈneɪtɪv/", "adj. 本土的/天生的 n. 本地人", "「na tiv」—— na tiv本土的 🏠", "Pandas are <b>native</b> to China."),
    "nausea": ("/ˈnɔːziə/", "n. 恶心/反胃/ nausea", "「no zi厄」—— no zi厄恶心 🤢", "The smell of rotten fish made her feel <b>nausea</b>."),
    "naval": ("/ˈneɪvl/", "adj. 海军的/军舰的", "「na vol」—— na vol海军 ⚓", "The country has a powerful <b>naval</b> fleet."),
    "navigable": ("/ˈnævɪɡəbl/", "adj. 可航行的/可通航的/可驾驶的", "「na vi ga伯」—— na vi ga伯可航行 ⛵", "The river became <b>navigable</b> again after the drought ended."),
    "neat": ("/niːt/", "adj. 整洁的/灵巧的/纯的", "「nit」—— nit整洁的 ✨", "Always keep your workspace <b>neat</b> and organized."),
    "necessitate": ("/nəˈsesɪteɪt/", "v. 使成为必要/需要/迫使", "「na ses提teit」—— na ses提teit需要 🔧", "The damage may <b>necessitate</b> a complete rebuild."),
    "needle": ("/ˈniːdl/", "n. 针/指针/针状物", "「ni dou」—— ni dou针 🪡", "Thread the <b>needle</b> before sewing the button."),
    "needy": ("/ˈniːdi/", "adj. 贫困的/需要帮助的 n. 穷人", "「ni di」—— ni di贫困的 🏚️", "The charity provides food for <b>needy</b> families."),
    "negation": ("/nɪˈɡeɪʃn/", "n. 否定/否认/ negation", "「ni geishen」—— ni geishen否定 ❌", "The <b>negation</b> of his claim required solid evidence."),
    "negative": ("/ˈneɡətɪv/", "adj. 否定的/消极的/负面的 n. 否定/底片", "「ne ga tiv」—— ne ga tiv消极的 😔", "Don't focus on the <b>negative</b> aspects of the situation."),
    "negligent": ("/ˈneɡlɪdʒənt/", "adj. 疏忽的/粗心大意玩忽职守的", "「ne li jen特」—— ne li jen特疏忽 ⚠️", "The doctor was found <b>negligent</b> in his duty."),
    "negligible": ("/ˈneɡlɪdʒəbl/", "adj. 可以忽略的/微不足道的", "「ne li ja伯」—— ne li ja伯可以忽略的 🤏", "The cost difference is <b>negligible</b>."),
    "negotiable": ("/nɪˈɡəʊʃiəbl/", "adj. 可协商的/可通过谈判解决的", "「ne gou shei伯」—— ne gou shei伯可协商 🤝", "The price is <b>negotiable</b> depending on quantity."),
    "nervous": ("/nɜːvəs/", "adj. 紧张的/神经的/神经质的", "「no vos」—— no vos紧张的 😬", "She felt <b>nervous</b> before her first performance."),
    "neutron": ("/ˈnjuːtrɒn/", "n. 中子", "「new特ron」—— new特ron中子 ⚛️", "A <b>neutron</b> has no electrical charge."),
    "nickel": ("/ˈnɪkl/", "n. 镍/镍币/五分硬币", "「ni kou」—— ni kou镍币 💰", "The alloy contains iron and <b>nickel</b>."),
    "nitrogen": ("/ˈnaɪtrədʒən/", "n. 氮/氮气", "「奈 tro jen」—— 奈 tro jen氮 🌿", "About seventy-eight percent of air is <b>nitrogen</b>."),
    "nobility": ("/nəʊˈbɪləti/", "n. 高贵/贵族阶级/高尚品质", "「nou bi li提」—— nou bi li提贵族 👑", "Her <b>nobility</b> of character inspired everyone around her."),
    "noisy": ("/ˈnɔɪzi/", "adj. 吵闹的/嘈杂的/喧哗的", "「noi zi」—— noi zi吵闹的 🔊", "The <b>noisy</b> neighbors kept us awake all night."),
    "nominal": ("/ˈnɒmɪnl/", "adj. 名义上的/微不足道的/ nominal", "「no mi nal」—— no mi nal名义上的 🏷️", "The position carries only a <b>nominal</b> salary."),
    "nomination": ("/ˌnɒmɪˈneɪʃn/", "n. 提名/任命/提名权", "「no mi neishen」—— no mi neishen提名 🏆", "She received an Oscar <b>nomination</b> for Best Actress."),
    "nonsense": ("/ˈnɒnsens/", "n. 胡说/废话/谬论", "「non sens」—— non sens胡说 🙅", "Stop talking <b>nonsense</b> and get back to work!"),
    "normally": ("/ˈnɔːməli/", "adv. 通常/正常地/一般", "「no mo 里」—— no mo里通常 😐", "<b>Normally</b>, I go jogging every morning."),
    "notably": ("/ˈnəʊtəbli/", "adv. 显著地/尤其/值得注意地", "「nou特伯里」—— nou特伯里显著 📌", "Several artists, most <b>notably</b> Picasso, changed art forever."),
    "note": ("/nəʊt/", "n. 笔记/笔记/音符 v. 注意/记录", "「nout」—— nout笔记 📝", "Make sure to <b>note</b> down the key points."),
    "nought": ("/nɔːt/", "n. 零/无/没有", "「not」—— not就是零 0⃣", "Multiply by <b>nought</b> and you get zero."),
    "nourishment": ("/ˈnʌrɪʃmənt/", "n. 食物/营养品/ nourishment", "「na ri sh ment」—— na ri sh ment营养 🥗", "Babies need proper <b>nourishment</b> to grow healthy."),
    "novel": ("/ˈnɒvl/", "n. 小说 adj. 新颖的/新奇的", "「no vel」—— no vel小说 📚", "She published her first <b>novel</b> at age twenty-five."),
    "nowadays": ("/ˈnaʊədeɪz/", "adv. 如今/现今/现在", "「now a deiz」—— now a deiz如今 📅", "<b>Nowadays</b>, most people own smartphones."),
    "nowhere": ("/ˈnəʊweə/", "adv. 任何地方都不/无处", "「no whe厄」—— no whe厄无处去 🚫", "The keys seem to have disappeared <b>nowhere</b> to be found."),
    "nuisance": ("/ˈnjuːsns/", "n. 麻烦事/讨厌的东西/妨害", "「new sens」—— new sens讨厌的事 😤", "Mosquitoes are a real <b>nuisance</b> in summer."),
    "null": ("/nʌl/", "adj. 无效的/零的 n. 空/零", "「那」—— 那是空的 0️⃣", "The contract was declared <b>null</b> and void."),
    "nullify": ("/ˈnʌlɪfaɪ/", "v. 使无效/废除/取消", "「那li fi」—— 那li fi使无效 ❌", "The supreme court may <b>nullify</b> the law."),
    "numerical": ("/njuːˈmerɪkl/", "adj. 数字的/数值的/用数字表示的", "「nu me瑞科」—— nu me瑞科数字的 🔢", "The report includes detailed <b>numerical</b> data."),
    "nursery": ("/nɜːsəri/", "n. 托儿所/苗圃/ nursery", "「na se瑞」—— na se瑞托儿所 👶", "She dropped her toddler off at the <b>nursery</b> before work."),
    "nylon": ("/ˈnaɪlɒn/", "n. 尼龙/ nylon", "「奈lon」—— 奈lon尼龙 🧵", "This bag is made of durable <b>nylon</b> material."),
    "oak": ("/əʊk/", "n. 橡树/橡木 adj. 橡木制的", "「oak」—— oak橡树 🌳", "The table is made of solid <b>oak</b>."),
    "oar": ("/ɔː/", "n. 桨/划桨 v. 划船", "「奥」—— 奥运划桨 🚣", "He pulled hard on the <b>oar</b> to move the boat faster."),
    "obedient": ("/əʊˈbiːdiənt/", "adj. 服从的/顺从的/听话的", "「ou bi di恩特」—— ou bi di恩特听话的 🐕", "The <b>obedient</b> dog sat when commanded."),
    "object": ("/ˈɒbdʒɪkt/", "n. 物体/目标 v. 反对/ objection", "「ob jekt」—— ob jekt物体 📦", "What is that strange <b>object</b> on the table?"),
    "oblige": ("/əˈblaɪdʒ/", "v. 强迫/施恩惠/ obligate", "「ou blai之」—— ou blai之强迫 🤝", "Could you <b>oblige</b> me by opening the door?"),
    "obliterate": (/əˈblɪtəreɪt/, "v. 消灭/抹去/彻底摧毁", "「ou blit 瑞teit」—— ou blit瑞teit消灭 💥", "The bombing <b>obliterated</b> the entire village."),
    "oblong": ("/ˈɒblɒŋ/", "adj. 长方形的/椭圆形的 n. 长方形", "「ou b隆」—— ou b隆长方形 ▭️", "The table has an <b>oblong</b> shape."),
    "observance": ("/əbˈzɜːvəns/", "n. 遵守/奉行/ observance", "「ob zerv恩斯」—— ob zerv恩斯遵守 📜", "Strict <b>observance</b> of safety protocols is mandatory."),
    "observe": ("/əbˈzɜːv/", "v. 观察/遵守/注意到", "「ob zerv」—— ob zerv观察 👀", "Scientists <b>observe</b> the stars through telescopes."),
    "obstinate": ("/ˈɒbstɪnət/", "adj. 固执的/顽固的/难以控制的", "「ob sti neit」—— ob sti neit固执的 🐂", "He remained <b>obstinate</b> despite all arguments."),
    "obstruction": ("/əbˈstrʌkʃn/", "n. 障碍物/阻塞/阻碍", "「ob strak shen」—— ob strak shen障碍 🚧", "Remove any <b>obstruction</b> from the exit immediately."),
    "obtainable": ("/əbˈteɪnəbl/", "adj. 可获得的/可取得的", "「ob tein 伯」—— ob tein伯可获得的 ✅", "Is this item still <b>obtainable</b> in stores?"),
    "occasional": ("/əˈkeɪʒənl/", "adj. 偶然的/临时的/特殊场合的", "「a kei shen nou」—— a kei shen nou偶尔 🎲", "I enjoy an <b>occasional</b> glass of wine with dinner."),
    "occasionally": ("/əˈkeɪʒənəli/", "adv. 偶尔/间或/有时", "「a kei shen那里」—— a kei shen那里偶尔 🎯", "She <b>occasionally</b> visits her grandparents on weekends."),
    "occurrence": ("/əˈkʌrəns/", "n. 发生/出现/事件", "「a kurns」—— a kurns发生事件 📅", "Such an <b>occurrence</b> is extremely rare."),
    "odour": ("/ˈəʊdə/", "n. 气味/臭味/ odour", "「ou de」—— ou de气味 👃", "A strange <b>odour</b> came from the kitchen."),
    "offence": ("/əˈfens/", "n. 犯罪/冒犯/进攻", "「a fen斯」—— a fen斯犯罪 ⚖️", "Speeding is a serious driving <b>offence</b>."),
    "offend": ("/əˈfend/", "v. 冒犯/得罪/使...不快", "「a fend」—— a fend冒犯 😡", "I didn't mean to <b>offend</b> anyone with my joke."),
    "offer": ("/ˈɒfə/", "n./v. 提供/提议/出价", "「o fer」—— o fer提供 🎁", "They decided to <b>offer</b> him the job."),
    "omen": ("/ˈəʊmen/", "n. 预兆/征兆/ omen", "「ou men」—— ou men预兆 🔮", "The black cat was considered a bad <b>omen</b>."),
    "omission": ("/əʊˈmɪʃn/", "n. 省略/遗漏/ omission", "「ou mi shen」—— ou mi shen遗漏 ⚠️", "The <b>omission</b> of her name from the list was noticed."),
    "omit": ("/əʊˈmɪt/", "v. 省略/遗漏/疏忽", "「ou mit」—— ou mit省略 📝", "Please don't <b>omit</b> any important details."),
    "opera": ("/ˈɒprə/", "n. 歌剧/歌剧艺术/ opera", "「o pr厄」—— o pr厄歌剧 🎭", "They went to see an Italian <b>opera</b> at the theater."),
    "operative": ("/ˈɒpərətɪv/", "adj. 有效的/运转中的 n. 侦探/工人", "「o pe 瑞提五」—— o pe瑞提五有效的 ✅", "The new regulation becomes <b>operative</b> next month."),
    "opinion": ("/əˈpɪnjən/", "n. 意见/看法/主张", "「o pin ion」—— o pin ion意见 💭", "Everyone is entitled to their own <b>opinion</b>."),
    "opportune": ("/ˌɒpəˈtjuːn/", "adj. 合适的/恰好的/及时的", "「o por tun」—— o por tun合适的 ⏰", "This is an <b>opportune</b> moment to discuss the matter."),
    "opportunity": ("/ˌɒpəˈtjuːnəti/", "n. 机会/时机/机遇", "「o por tun提」—— o por tun提机会 🚀", "Don't miss this wonderful <b>opportunity</b> to travel abroad."),
    "oppose": ("/əˈpəʊz/", "v. 反对/反抗/抗争", "「ou pouz」—— ou pouz反对 🚫", "Many residents <b>oppose</b> the construction of the new highway."),
    "opposite": ("/ˈɒpəzɪt/", "adj. 对面的/相反的 n. 对立面/对立物", "「o po sit」—— o po sit相反的 ↔️", "She sat on the <b>opposite</b> side of the table."),
    "opposition": ("/ˌɒpəˈzɪʃn/", "n. 反对/反对派/ opposition", "「o po zi shen」—— o po zi shen反对派 ⚔️", "The proposal faced strong <b>opposition</b> from environmental groups."),
    "oppress": ("/əˈpres/", "v. 压迫/压制/使烦恼", "「o press」—— o press压迫 ⛓️", "The dictator <b>oppressed</b> his people for decades."),
    "optical": ("/ˈɒptɪkl/", "adj. 光学的/视觉的/眼睛的", "「op ti ko」—— op ti ko光学的 👓", "Telescopes use advanced <b>optical</b> technology."),
    "optimum": ("/ˈɒptɪməm/", "adj. 最优的/最佳的 n. 最佳条件", "「op ti mum」—— op ti mum最佳 ✅", "Plants grow best under <b>optimum</b> conditions of light and water."),
    "optional": ("/ˈɒpʃənl/", "adj. 可选择的/非强制性的", "「op shen nou」—— op shen nou可选的 🔘", "Attendance at the seminar is <b>optional</b>."),
    "orbit": ("/ˈɔːbɪt/", "n. 轨道 v. 沿轨道运行/环绕运行", "「o bit」—— o bit轨道 🛰️", "The satellite maintains a stable <b>orbit</b> around Earth."),
    "orchard": ("/ˈɔːtʃəd/", "n. 果园/果园", "「o chad」—— o chad果园 🍎", "We picked apples in the apple <b>orchard</b> last autumn."),
    "orchestra": ("/ˈɔːkɪstrə/", "n. 管弦乐队/管弦乐团", "「o ki str厄」—— o ki str厄乐队 🎻", "The symphony <b>orchestra</b> gave a brilliant performance."),
    "ordeal": ("/ɔːˈdiːl/", "n. 严峻考验/折磨/苦难经历", "「o di ou」—— o di ou严峻考验 😰", "Surviving the shipwreck was a terrible <b>ordeal</b>."),
    "orderly": ("/ˈɔːdəli/", "adj. 有秩序的/整齐的 adv. 依次地", "「o der li」—— o der li有序的 ✅", "Please arrange the books in an <b>orderly</b> fashion."),
    "ore": ("/ɔː/", "n. 矿石/矿砂", "「o」—— o就是矿石 ⛏️", "The region is rich in iron <b>ore</b>."),
    "organism": ("/ˈɔːɡənɪzəm/", "n. 生物/有机体/微生物", "「o gan izem」—— o gan izem生物 🦠", "Every living <b>organism</b> needs water to survive."),
    "oriental": ("/ˌɔːriˈentl/", "adj. 东方的/东方风格的 n. 东方人", "「o ri en tou」—— o ri en tou东方的 🏯", "She studied <b>Oriental</b> languages at university."),
    "origin": ("/ˈɒrɪdʒɪn/", "n. 起源/出身/源头", "「o瑞金」—— o瑞金的起源 🌱", "The <b>origin</b> of the custom dates back centuries."),
    "original": ("/əˈrɪdʒənl/", "adj. 最初的/原始的/新颖的 n. 原件/原作", "「o瑞吉nou」—— o瑞吉nou最初的 🎨", "This is the <b>original</b> painting, not a copy."),
    "originality": ("/ˌrɪdʒəˈnæləti/", "n. 独创性/创意/ originality", "「o瑞吉那里提」—— o瑞吉那里提独创性 💡", "Her designs are admired for their <b>originality</b>."),
    "ornament": ("/ˈɔːnəmənt/", "n. 装饰品/装饰 v. 装饰/美化", "「o na ment」—— o na ment装饰品 🎄", "The Christmas tree was adorned with colorful <b>ornaments</b>."),
    "ornamental": ("/ˌɔːnəˈmentl/", "adj. 装饰性的/装饰用的/ ornamental", "「o na men tou」—— o na men tou装饰的 🏺", "The vase is purely <b>ornamental</b>, not functional."),
    "oscillate": ("/ˈɒsɪleɪt/", "v. 摆动/振荡/动摇", "「o sei leit」—— o sei leit摆动 📊", "Stock prices continue to <b>oscillate</b> wildly."),
    "ostensible": ("/ɒˈstensəbl/", "adj. 表面上的/假装的/ ostensible", "「o ten si伯」—— o ten si伯表面的 🎭", "The <b>ostensible</b> reason for the meeting was different from reality."),
    "ounce": ("/aʊns/", "n. 盎司/少量/ ounce", "「aun斯」—— aun斯盎司 ⚖️", "Add just an <b>ounce</b> of sugar to the recipe."),
    "outdoors": ("/ˌaʊtˈdɔːz/", "adv. 在户外/在野外 n. 户外/野外", "「a ut道兹」—— a ut道兹户外 🌲", "Children love playing <b>outdoors</b> in summer."),
    "outermost": ("/ˈaʊtəməʊst/", "adj. 最外面的/最远的", "「a utmost」—— a utmost最外面的 🔭", "The <b>outermost</b> planet in our solar system is Neptune."),
    "outlandish": ("/aʊtˈlændɪʃ/", "adj. 古怪的/稀奇古怪的/外国气的", "「a ut lan dish」—— a ut lan dish古怪的 🤪", "His <b>outlandish</b> costume attracted attention at the party."),
    "outlaw": ("/ˈaʊtlɔː/", "n. 歹徒/逃犯 v. 宣布非法/取缔", "「a ut劳」—— a ut劳歹徒 🏴‍☠️", "The government plans to <b>outlaw</b> single-use plastics."),
    "outlet": ("/ˈaʊtlet/", "n. 出口/ outlet/经销店", "「a ut let」—— a ut let出口 🚪", "Find the nearest power <b>outlet</b> to plug in the charger."),
    "outline": ("/ˈaʊtlaɪn/", "n. 大纲/轮廓/概要 v. 概述/勾勒", "「a ut莱恩」—— a ut莱恩大纲 📋", "Let me briefly <b>outline</b> my plan for the project."),
    "outrageous": ("/aʊtˈreɪdʒəs/", "adj. 令人震惊的/无法无天的/蛮横的", "「a ut rei jus」—— a ut rei jus令人震惊 😱", "The prices at that restaurant are absolutely <b>outrageous</b>."),
    "outright": ("/ˈaʊtraɪt/", "adv. 彻底的/直率的/完全的 adj. 完全的/直率的", "「a ut瑞特」—— a ut瑞特完全的 💯", "He rejected the offer <b>outright</b>."),
    "outset": ("/ˈaʊtset/", "n. 开始/开端/ outset", "「a utset」—— a utset开始 🏁", "From the <b>outset</b>, the project faced difficulties."),
    "outweigh": ("/ˌaʊtˈweɪ/", "v. 比...更重要/胜过/超过", "「a ut wei」—— a ut wei胜过 ⚖️", "The benefits far <b>outweigh</b> the risks."),
    "oval": ("/əʊvl/", "adj. 椭圆形的 n. 椭圆形/椭圆跑道", "「o vol」—— o vol椭圆形 🥚", "The mirror has an <b>oval</b> shape."),
    "overall": ("/ˌəʊvərɔːl/", "adj. 全面的/总体的 adv. 总的来说/大体上", "「o ver o」—— o ver o总体 📊", "<b>Overall</b>, the event was a great success."),
    "overcast": ("/əʊvəˈkɑːst/", "adj. 多云的/阴天的 v. 使阴暗/遮盖", "「o ver kas」—— o ver kas多云的 ☁️", "The sky was <b>overcast</b>, threatening rain."),
    "overcharge": ("/ˌəʊvəˈtʃɑːdʒ/", "v. 索价过高/过量充电 n. 过高的收费", "「o ver cha治」—— o ver cha治多收费 💸", "The taxi driver tried to <b>overcharge</b> me."),
    "overestimate": ("/ˌəʊvərˈestɪmeɪt/", "v. 高估/估计过高", "「o ver es提meit」—— o ver es提meit高估 📈", "Don't <b>overestimate</b> your ability to finish this task."),
    "overflow": ("/ˌəʊvəˈfləʊ/", "v. 溢出/泛滥 n. 溢出物/溢水口", "「o ver flow」—— o ver flow溢出 💧", "The river <b>overflowed</b> its banks after heavy rain."),
    "overhaul": ("/ˌəʊvəˈhɔːl/", "v. 大修/彻底改革 n. 大修/全面检查", "「o ver hol」—— o ver hol大修 🔧", "The engine needs a complete <b>overhaul</b> before racing season."),
    "overhear": ("/ˌəʊvəˈhɪə/", "v. 无意听到/偷听到", "「o ver hi厄」—— o ver hi厄偷听 👂", "I accidentally <b>overheard</b> their conversation."),
    "overlapping": ("/ˌəʊvəˈlæpɪŋ/", "adj. 重叠的/部分重叠的", "「o ver la ping」—— o ver la ping重叠的 📑", "The two events have <b>overlapping</b> schedules."),
    "overload": ("/ˌəʊvəˈləʊd/", "v. 使超载/使负担过重 n. 超载/过载", "「o ver loud」—— o ver loud超载 ⚠️", "Don't <b>overload</b> the washing machine."),
    "override": ("/ˌəʊvəˈraɪd/", "v. 推翻/凌驾/覆盖", "「o ver瑞deit」—— o ver瑞deit推翻 🔄", "The committee voted to <b>override</b> the veto."),
    "oversight": ("/ˈəʊvəsaɪt/", "n. 疏忽/监督/ oversight", "「o ver赛特」—— o ver赛特监督 👀", "The error was due to an administrative <b>oversight</b>."),
    "overthrow": ("/ˌəʊvəˈθrəʊ/", "v. 推翻/打倒 n. 推翻/颠覆", "「o ver throw」—— o ver throw推翻 🏚️", "The revolution aimed to <b>overthrow</b> the dictatorship."),
    "overtime": ("/əʊvətaɪm/", "n./adv. 加班/加班时间 adj. 超时的", "「o ver tim」—— o ver tim加班 ⏰", "She worked <b>overtime</b> to finish the report."),
    "overwhelming": ("/ˌəʊvəˈwelmɪŋ/", "adj. 压倒性的/势不可挡的/令人不知所措的", "「o ver wel ming」—— o ver wel ming压倒性的 💥", "There was <b>overwhelming</b> support for the new policy."),
    "owe": ("/əʊ/", "v. 欠/应该把...归功于", "「o」—— o欠债 💳", "I still <b>owe</b> him money for the tickets."),
    "owl": ("/aʊl/", "n. 猫头鹰/ owl", "「ao」—— ao猫头鹰 🦉", "The <b>owl</b> hooted in the night sky."),
    "own": ("/əʊn/", "adj. 自己的 v. 拥有/承认", "「on」—— on自己的 🏠", "She finally bought her <b>own</b> apartment."),
    "oxide": ("/ˈɒksaɪd/", "n. 氧化物", "「ok sai d」—— ok sai d氧化物 ⚗️", "Rust is iron <b>oxide</b>."),
    "oxygen": ("/ˈɒksɪdʒən/", "n. 氧气/氧元素", "「ok si jen」—— ok si jen氧气 🫁", "Humans cannot survive without <b>oxygen</b>."),
    "oyster": ("/ɔɪstə/", "n. 牡蛎/蚝/ oyster", "「oi斯特」—— oi斯特牡蛎 🦪", "Fresh <b>oysters</b> are a delicacy in this region."),

    # ===== WORDBOOK 52 (401-487, #5101-#5187): orbit -> perfect =====
    # Already generated as wordbook-52.md - SKIP
}

print(f"Loaded {len(WORD_DATA)} word entries")
